### ISSUE TITLE
Nicer heads while moving

### ISSUE THREAD

**Issue by prdwong** [krelbel/ALttPLinkSpriteShuffler#1]
Since the heads most common seen throughout the game are just Link moving around the world, I wanted to concentrate on making those nicer than just pure random. Specifically, the problem is that the sideways walking/dashing animation consists of 3 head sprites (up and down only use a single head sprite). So instead of sideways movement being a confusing mess  I locked those 3 head sprites to all face the same direction (they all must be side sprites, up sprites, or down sprites).

I think I like it a little better, don't know if you want to consider such a feature.

**Comment by krelbel** [comment]
Good idea; fixed in 0.3
